remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Kaleidoscope FBLA Wisconsin
description: website where all our fbla antics are stored
github:
  repository_url: http://github.com/LithiumYing/Kaleidscope
